"""Mapping for Android app packages and common website URLs to readable names."""
# Add more entries as you discover them!

# Android app packages that don't match their readable names
ANDROID_MAPPING = {
    'com.zhiliaoapp.musically': ['TikTok'], # Yes, this is the package name
    'com.facebook.katana': ['Facebook'],
    'com.facebook.orca': ['Facebook Messenger', 'Messenger'],
    'com.soundbrenner.pulse': ['Soundbrenner Metronome'],
    'com.lunarlabsoftware.grouploop': ['Group Loop'],
    'com.naver.linewebtoon': ['Webtoon'],
    'com.paprbit.dcoder': ['DCodeR'],
    'com.wizards.mtga': ['Magic: The Gathering Arena'],
    'com.emagroups.tdo': ['The Dragon Oddyssey'],
    'com.companyname.MaturaMatematyka': ['1st-12th Grade Math Problems'],
    'com.ichi2.anki': ['AnkiDroid', 'AnkiWeb'],
    'com.atistudios.italk.es': ['Learn Spanish. Speak Spanish'],

    # Common Google Apps
    'com.google.android.gm': ['Gmail'],
    'com.google.android.apps.maps': ['Google Maps'],
    'com.google.android.youtube': ['YouTube'],
    'com.google.android.apps.docs': ['Google Docs'],
    'com.google.android.apps.drive': ['Google Drive'],
    'com.google.android.apps.photos': ['Google Photos'],
    'com.google.android.calendar': ['Google Calendar'],
    'com.google.android.keep': ['Google Keep'],
    'com.google.android.apps.meetings': ['Google Meet'],
    'com.google.android.talk': ['Google Chat', 'Hangouts'],
    'com.google.android.apps.translate': ['Google Translate'],
    'com.android.chrome': ['Chrome'],
    
    # Social Media & Communication
    'com.whatsapp': ['WhatsApp'],
    'com.instagram.android': ['Instagram'],
    'com.twitter.android': ['Twitter', 'X'],
    'com.linkedin.android': ['LinkedIn'],
    'com.snapchat.android': ['Snapchat'],
    'com.discord': ['Discord'],
    'org.telegram.messenger': ['Telegram'],
    'org.thoughtcrime.securesms': ['Signal'],
    'com.pinterest': ['Pinterest'],
    'com.tumblr': ['Tumblr'],
    'com.reddit.frontpage': ['Reddit'],
    'com.viber.voip': ['Viber'],
    'com.kakao.talk': ['KakaoTalk'],
    'jp.naver.line.android': ['Line'],
    'com.tencent.mm': ['WeChat'],
    
    # Entertainment & Streaming
    'com.spotify.music': ['Spotify'],
    'com.netflix.mediaclient': ['Netflix'],
    'com.disney.disneyplus': ['Disney+', 'Disney Plus'],
    'com.hulu.plus': ['Hulu'],
    'com.amazon.avod.thirdpartyclient': ['Prime Video'],
    'com.hbo.hbonow': ['HBO Max'],
    'com.twitch.android.app': ['Twitch'],
    'com.google.android.youtube.tv': ['YouTube TV'],
    'com.pandora.android': ['Pandora'],
    'com.apple.android.music': ['Apple Music'],
    'com.amazon.mp3': ['Amazon Music'],
    'deezer.android.app': ['Deezer'],
    'com.soundcloud.android': ['SoundCloud'],
    'com.audible.application': ['Audible'],
    
    # Gaming
    'com.pubg.imobile': ['PUBG Mobile'],
    'com.activision.callofduty.shooter': ['Call of Duty Mobile'],
    'com.epicgames.fortnite': ['Fortnite'],
    'com.miHoYo.GenshinImpact': ['Genshin Impact'],
    'com.mojang.minecraftpe': ['Minecraft'],
    'com.roblox.client': ['Roblox'],
    'com.supercell.clashofclans': ['Clash of Clans'],
    'com.supercell.clashroyale': ['Clash Royale'],
    'com.innersloth.spacemafia': ['Among Us'],
    'com.nianticlabs.pokemongo': ['Pokémon GO'],
    'com.king.candycrushsaga': ['Candy Crush Saga'],
    'com.mobile.legends': ['Mobile Legends'],
    'com.ea.gp.fifamobile': ['FIFA Mobile'],
    'com.gameloft.android.ANMP.GloftA8HM': ['Asphalt 8'],
    'com.valvesoftware.android.steam.community': ['Steam'],
    'com.ninjakiwi.bloonstd6': ['Bloons TD 6'],
    'com.ninjakiwi.bloonstd5': ['Bloons TD 5'],
    'com.ninjakiwi.bloonstdbattles': ['Bloons TD Battles'],
    
    # Shopping & E-commerce  
    'com.amazon.mshop.android.shopping': ['Amazon'],
    'com.ebay.mobile': ['eBay'],
    'com.etsy.android': ['Etsy'],
    'com.contextlogic.wish': ['Wish'],
    'com.alibaba.aliexpresshd': ['AliExpress'],
    'com.walmart.android': ['Walmart'],
    'com.target.ui': ['Target'],
    
    # Finance & Banking
    'com.paypal.android.p2pmobile': ['PayPal'],
    'com.venmo': ['Venmo'],
    'com.squareup.cash': ['Cash App'],
    'com.robinhood.android': ['Robinhood'],
    'com.coinbase.android': ['Coinbase'],
    'org.toshi': ['Coinbase Wallet'],
    'piuk.blockchain.android': ['Blockchain Wallet'],
    'com.plaid.link': ['Plaid'],
    
    # Productivity & Work
    'com.dropbox.android': ['Dropbox'],
    'com.microsoft.office.outlook': ['Outlook'],
    'com.skype.raider': ['Skype'],
    'com.slack': ['Slack'],
    'us.zoom.videomeetings': ['Zoom'],
    'com.microsoft.teams': ['Microsoft Teams', 'Teams'],
    'so.oneapp.notion': ['Notion'],
    'com.asana.app': ['Asana'],
    'com.trello': ['Trello'],
    'com.todoist': ['Todoist'],
    'com.evernote': ['Evernote'],
    'com.microsoft.office.onenote': ['OneNote'],
    'com.google.android.apps.docs.editors.sheets': ['Google Sheets'],
    'com.google.android.apps.docs.editors.slides': ['Google Slides'],
    'com.adobe.reader': ['Adobe Acrobat'],
    'com.canva.editor': ['Canva'],
    
    # Health & Fitness
    'com.myfitnesspal.android': ['MyFitnessPal'],
    'com.fitbit.FitbitMobile': ['Fitbit'],
    'com.strava': ['Strava'],
    'com.nike.plusone': ['Nike Training Club'],
    'com.nike.snkrs': ['Nike SNKRS'],
    'com.adidas.app': ['Adidas'],
    'com.peloton.callisto': ['Peloton'],
    'com.gethealthify.healthifymeCalorie': ['Healthify Me'],
    'com.headspace.android': ['Headspace'],
    'com.calm.android': ['Calm'],
    'com.webmd.android': ['WebMD'],
    
    # Education & Learning
    'com.duolingo': ['Duolingo'],
    'org.khanacademy.android': ['Khan Academy'],
    'org.coursera.android': ['Coursera'],
    'com.udemy.android': ['Udemy'],
    'com.memrise.android.memrisecompanion': ['Memrise'],
    'com.babbel.mobile.android.en': ['Babbel'],
    'com.rosettastone.mobile.CoursePlayer': ['Rosetta Stone'],
    'com.skillshare.Skillshare': ['Skillshare'],
    'com.lynda.android': ['LinkedIn Learning'],
    'com.pluralsight': ['Pluralsight'],
    'com.codecademy.mobile': ['Codecademy'],
    
    # Transportation & Food Delivery
    'com.ubercab': ['Uber'],
    'me.lyft.android': ['Lyft'],
    'com.dd.doordash': ['DoorDash'],
    'com.grubhub.android': ['GrubHub'],
    'com.ubereats': ['Uber Eats'],
    'com.postmates.android': ['Postmates'],
    'com.instacart.client': ['Instacart'],
    
    # Dating & Social
    'com.tinder': ['Tinder'],
    'com.bumble.app': ['Bumble'],
    'co.hinge.app': ['Hinge'],
    'com.match.android.matchmobile': ['Match'],
    'com.pof.android': ['Plenty of Fish'],
    'com.okcupid.okcupid': ['OkCupid'],
    
    # News & Reading
    'flipboard.app': ['Flipboard'],
    'com.medium.reader': ['Medium'],
    'com.google.android.apps.magazines': ['Google News'],
    'com.cnn.mobile.android.phone': ['CNN'],
    'com.nytimes.android': ['New York Times'],
    'com.washingtonpost.rainbow': ['Washington Post'],
    'com.clearchannel.iheartradio.controller': ['iHeartRadio'],
    
    # Cloud Storage & File Management
    'com.microsoft.skydrive': ['OneDrive'],
    'com.box.android': ['Box'],
    'nz.mega.android': ['MEGA'],
    'com.pcloud.pcloud': ['pCloud'],
    
    # Password Managers & Security
    'com.bitwarden.mobile': ['Bitwarden'],
    'com.lastpass.lpandroid': ['LastPass'],
    'com.agilebits.onepassword': ['1Password'],
    'com.dashlane': ['Dashlane'],
    'com.authy.authy': ['Authy'],
    'com.google.android.apps.authenticator2': ['Google Authenticator'],
    'com.microsoft.authenticator': ['Microsoft Authenticator'],
}

# Common website URLs/domains mapped to readable names
URL_MAPPING = {
    # Google Services
    'accounts.google.com': ['Google Account', 'Google'],
    'mail.google.com': ['Gmail'],
    'drive.google.com': ['Google Drive'],
    'docs.google.com': ['Google Docs'],
    'sheets.google.com': ['Google Sheets'],
    'slides.google.com': ['Google Slides'],
    'photos.google.com': ['Google Photos'],
    'calendar.google.com': ['Google Calendar'],
    'play.google.com': ['Google Play Store'],
    'maps.google.com': ['Google Maps'],
    'translate.google.com': ['Google Translate'],
    'keep.google.com': ['Google Keep'],
    'cloud.google.com': ['Google Cloud'],
    'firebase.google.com': ['Firebase'],
    'console.cloud.google.com': ['Google Cloud Console'],

    # Microsoft Services
    'outlook.live.com': ['Outlook', 'Microsoft Outlook'],
    'login.live.com': ['Microsoft Account', 'Microsoft'],
    'portal.office.com': ['Office 365', 'Microsoft Office', 'Office', 'Office'],
    'onedrive.live.com': ['OneDrive'],
    'teams.microsoft.com': ['Microsoft Teams', 'Teams', 'Teams'],
    'login.microsoftonline.com': ['Microsoft 365'],
    'azure.microsoft.com': ['Microsoft Azure', 'Azure', 'Azure'],
    'portal.azure.com': ['Azure Portal'],
    'dev.azure.com': ['Azure DevOps'],
    'store.microsoft.com': ['Microsoft Store'],

    # Social Media & Communication
    'facebook.com': ['Facebook'],
    'instagram.com': ['Instagram'],
    'twitter.com': ['X', 'Twitter'],
    'x.com': ['X', 'Twitter'],
    'linkedin.com': ['LinkedIn'],
    'snapchat.com': ['Snapchat'],
    'tiktok.com': ['TikTok'],
    'pinterest.com': ['Pinterest'],
    'tumblr.com': ['Tumblr'],
    'reddit.com': ['Reddit'],
    'discord.com': ['Discord'],
    'telegram.org': ['Telegram'],
    'whatsapp.com': ['WhatsApp'],
    'signal.org': ['Signal'],
    'mastodon.social': ['Mastodon'],
    'threads.net': ['Threads'],
    'clubhouse.com': ['Clubhouse'],

    # Professional & Work
    'slack.com': ['Slack'],
    'zoom.us': ['Zoom'],
    'meet.google.com': ['Google Meet', 'Meet', 'Meet'],
    'webex.com': ['Cisco Webex'],
    'gotomeeting.com': ['GoToMeeting'],
    'notion.so': ['Notion'],
    'asana.com': ['Asana'],
    'trello.com': ['Trello'],
    'monday.com': ['Monday.com'],
    'clickup.com': ['ClickUp'],
    'basecamp.com': ['Basecamp'],
    'jira.atlassian.com': ['Jira'],
    'confluence.atlassian.com': ['Confluence'],
    'bitbucket.org': ['Bitbucket'],
    'gitlab.com': ['GitLab'],

    # Developer Tools & Code
    'github.com': ['GitHub'],
    'stackoverflow.com': ['Stack Overflow', 'StackOverflow'],
    'codepen.io': ['CodePen'],
    'replit.com': ['Replit'],
    'heroku.com': ['Heroku'],
    'vercel.com': ['Vercel'],
    'netlify.com': ['Netlify'],
    'digitalocean.com': ['DigitalOcean'],
    'aws.amazon.com': ['Amazon Web Services', 'AWS'],
    'console.aws.amazon.com': ['AWS Console'],
    'npmjs.com': ['npm'],
    'pypi.org': ['PyPI'],
    'docker.com': ['Docker'],
    'kubernetes.io': ['Kubernetes'],

    # Streaming & Entertainment
    'netflix.com': ['Netflix'],
    'disney.com': ['Disney+'],
    'disneyplus.com': ['Disney+', 'Disney Plus'],
    'hulu.com': ['Hulu'],
    'primevideo.com': ['Amazon Prime Video', 'Prime Video'],
    'hbomax.com': ['HBO Max'],
    'max.com': ['Max'],
    'paramount.com': ['Paramount+'],
    'peacocktv.com': ['Peacock'],
    'crunchyroll.com': ['Crunchyroll'],
    'funimation.com': ['Funimation'],
    'twitch.tv': ['Twitch'],
    'youtube.com': ['YouTube'],
    'vimeo.com': ['Vimeo'],
    'dailymotion.com': ['Dailymotion'],

    # Music & Audio
    'spotify.com': ['Spotify'],
    'music.apple.com': ['Apple Music'],
    'music.amazon.com': ['Amazon Music'],
    'music.youtube.com': ['YouTube Music', 'YT Music'],
    'pandora.com': ['Pandora'],
    'soundcloud.com': ['SoundCloud'],
    'bandcamp.com': ['Bandcamp'],
    'tidal.com': ['Tidal'],
    'deezer.com': ['Deezer'],
    'audible.com': ['Audible'],
    'podcast.app': ['Podcast App'],

    # Shopping & E-commerce
    'amazon.com': ['Amazon'],
    'ebay.com': ['eBay'],
    'walmart.com': ['Walmart'],
    'target.com': ['Target'],
    'costco.com': ['Costco'],
    'bestbuy.com': ['Best Buy'],
    'homedepot.com': ['Home Depot'],
    'lowes.com': ['Lowes'],
    'etsy.com': ['Etsy'],
    'shopify.com': ['Shopify'],
    'aliexpress.com': ['AliExpress'],
    'alibaba.com': ['Alibaba'],
    'wish.com': ['Wish'],
    'overstock.com': ['Overstock'],
    'wayfair.com': ['Wayfair'],

    # Banking & Finance
    'paypal.com': ['PayPal'],
    'venmo.com': ['Venmo'],
    'cashapp.com': ['Cash App'],
    'zelle.com': ['Zelle'],
    'mint.com': ['Mint'],
    'creditkarma.com': ['Credit Karma'],
    'nerdwallet.com': ['NerdWallet'],
    'personalcapital.com': ['Personal Capital'],
    'robinhood.com': ['Robinhood'],
    'fidelity.com': ['Fidelity'],
    'schwab.com': ['Charles Schwab'],
    'etrade.com': ['E*TRADE'],
    'wellsfargo.com': ['Wells Fargo'],
    'bankofamerica.com': ['Bank of America'],
    'chase.com': ['Chase'],
    'capitalone.com': ['Capital One'],
    'discover.com': ['Discover'],
    'americanexpress.com': ['American Express'],

    # Gaming
    'steam.com': ['Steam'],
    'epicgames.com': ['Epic Games'],
    'ea.com': ['EA'],
    'origin.com': ['Origin'],
    'ubisoft.com': ['Ubisoft'],
    'blizzard.com': ['Blizzard'],
    'battle.net': ['Battle.net'],
    'rockstargames.com': ['Rockstar Games'],
    'nintendo.com': ['Nintendo'],
    'playstation.com': ['PlayStation'],
    'xbox.com': ['Xbox'],
    'itch.io': ['itch.io'],
    'gog.com': ['GOG'],
    'humblebundle.com': ['Humble Bundle'],

    # Cloud Storage & File Sharing
    'dropbox.com': ['Dropbox'],
    'box.com': ['Box'],
    'mega.nz': ['MEGA'],
    'icloud.com': ['iCloud'],
    'pcloud.com': ['pCloud'],
    'sync.com': ['Sync.com'],
    'mediafire.com': ['MediaFire'],
    '4shared.com': ['4shared'],
    'wetransfer.com': ['WeTransfer'],
    'sendspace.com': ['SendSpace'],

    # Education & Learning
    'coursera.org': ['Coursera'],
    'udemy.com': ['Udemy'],
    'edx.org': ['edX'],
    'khanacademy.org': ['Khan Academy'],
    'skillshare.com': ['Skillshare'],
    'lynda.com': ['Lynda'],
    'linkedin.com/learning': ['LinkedIn Learning'],
    'pluralsight.com': ['Pluralsight'],
    'codecademy.com': ['Codecademy'],
    'freecodecamp.org': ['freeCodeCamp'],
    'duolingo.com': ['Duolingo'],
    'babbel.com': ['Babbel'],
    'rosettastone.com': ['Rosetta Stone'],

    # News & Media
    'cnn.com': ['CNN'],
    'bbc.com': ['BBC'],
    'nytimes.com': ['New York Times'],
    'washingtonpost.com': ['Washington Post'],
    'wsj.com': ['Wall Street Journal'],
    'reuters.com': ['Reuters'],
    'ap.org': ['Associated Press'],
    'npr.org': ['NPR'],
    'medium.com': ['Medium'],
    'substack.com': ['Substack'],
    'news.ycombinator.com': ['Hacker News'],
    'techcrunch.com': ['TechCrunch'],
    'theverge.com': ['The Verge'],
    'wired.com': ['Wired'],

    # Travel & Transportation
    'booking.com': ['Booking.com'],
    'expedia.com': ['Expedia'],
    'kayak.com': ['Kayak'],
    'priceline.com': ['Priceline'],
    'hotels.com': ['Hotels.com'],
    'airbnb.com': ['Airbnb'],
    'vrbo.com': ['VRBO'],
    'uber.com': ['Uber'],
    'lyft.com': ['Lyft'],
    'delta.com': ['Delta Airlines'],
    'united.com': ['United Airlines'],
    'american.com': ['American Airlines'],
    'southwest.com': ['Southwest Airlines'],
    'jetblue.com': ['JetBlue'],

    # Health & Fitness
    'myfitnesspal.com': ['MyFitnessPal'],
    'fitbit.com': ['Fitbit'],
    'strava.com': ['Strava'],
    'nike.com': ['Nike'],
    'adidas.com': ['Adidas'],
    'peloton.com': ['Peloton'],
    'headspace.com': ['Headspace'],
    'calm.com': ['Calm'],
    'webmd.com': ['WebMD'],
    'mayoclinic.org': ['Mayo Clinic'],

    # Productivity & Organization
    'evernote.com': ['Evernote'],
    'onenote.com': ['OneNote'],
    'todoist.com': ['Todoist'],
    'any.do': ['Any.do'],
    'wunderlist.com': ['Wunderlist'],
    'airtable.com': ['Airtable'],
    'zapier.com': ['Zapier'],
    'ifttt.com': ['IFTTT'],
    'calendly.com': ['Calendly'],
    'doodle.com': ['Doodle'],

    # Password Managers & Security
    'bitwarden.com': ['Bitwarden'],
    'lastpass.com': ['LastPass'],
    '1password.com': ['1Password'],
    'dashlane.com': ['Dashlane'],
    'keepass.info': ['KeePass'],
    'nordpass.com': ['NordPass'],
    'authy.com': ['Authy'],
    'okta.com': ['Okta'],
    'duo.com': ['Duo Security'],

    # VPN & Privacy
    'nordvpn.com': ['NordVPN'],
    'expressvpn.com': ['ExpressVPN'],
    'surfshark.com': ['Surfshark'],
    'cyberghostvpn.com': ['CyberGhost'],
    'privateinternetaccess.com': ['Private Internet Access'],
    'protonmail.com': ['ProtonMail'],
    'protonvpn.com': ['ProtonVPN'],
    'tutanota.com': ['Tutanota'],

    # Miscellaneous Popular Sites
    'wikipedia.org': ['Wikipedia'],
    'archive.org': ['Internet Archive'],
    'quora.com': ['Quora'],
    'yelp.com': ['Yelp'],
    'tripadvisor.com': ['TripAdvisor'],
    'goodreads.com': ['Goodreads'],
    'imdb.com': ['IMDb'],
    'rotten tomatoes.com': ['Rotten Tomatoes'],
    'metacritic.com': ['Metacritic'],
    'weather.com': ['Weather.com'],
    'accuweather.com': ['AccuWeather'],
}
